export default function AIExplanation({ explanation }) {
  return (
    <div className="bg-gradient-to-br from-primary-50 to-[#f3e8ff] rounded-2xl p-6 md:p-8 border border-primary-100 shadow-sm relative overflow-hidden">
      {/* Decorative background element */}
      <div className="absolute top-0 right-0 -mt-16 -mr-16 w-64 h-64 bg-white opacity-40 rounded-full blur-3xl"></div>
      
      <div className="relative z-10">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center text-xl">
            ✨
          </div>
          <div>
            <h3 className="text-xl font-display font-bold text-surface-900">AI-Powered Analysis</h3>
            <p className="text-xs text-surface-500 font-medium">Generated by Google Gemini based on simulation statistics</p>
          </div>
        </div>

        {!explanation ? (
          <div className="space-y-4">
            <div className="h-4 bg-white/60 rounded animate-pulse w-3/4"></div>
            <div className="h-4 bg-white/60 rounded animate-pulse w-full"></div>
            <div className="h-4 bg-white/60 rounded animate-pulse w-5/6"></div>
            <div className="h-4 bg-white/60 rounded animate-pulse w-full"></div>
            <div className="h-4 bg-white/60 rounded animate-pulse w-2/3"></div>
          </div>
        ) : (
          <div className="prose prose-sm md:prose-base prose-slate max-w-none text-surface-800 leading-relaxed space-y-4">
            {explanation.split('\n').filter(p => p.trim() !== '').map((paragraph, i) => (
              <p key={i}>{paragraph}</p>
            ))}
          </div>
        )}
        
        <div className="mt-8 pt-4 border-t border-white/50 text-xs text-surface-500">
          <strong>Note:</strong> The numbers in the charts above are computed via Monte Carlo simulation. This text is an AI interpretation to help you understand the dynamics.
        </div>
      </div>
    </div>
  );
}
